name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Copy files to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_DNS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            git config --global --add safe.directory /var/www/homeServer

            if [ ! -d "/var/www/homeServer/.git" ]; then
              git clone https://github.com/amr_imad/homeServer.git /var/www/homeServer
            else
              cd /var/www/homeServer
              git pull origin main
            fi

            cd /var/www/homeServer

            # Load NVM properly
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            nvm use 24

            node -v
            npm -v

            npm install

            pm2 restart homeServer || pm2 start server.js --name homeServer
