name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Copy files to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_DNS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            if [ ! -d "/var/www/homeServer/.git" ]; then
              git clone https://github.com/amr-imad/homeServer.git /var/www/homeServer
            else
              cd /var/www/homeServer
              git pull origin main
            fi

            cd /var/www/homeServer
            npm install

            pm2 restart homeServer || pm2 start server.js --name homeServer
